
ALTER TABLE Client ADD COLUMN Email VARCHAR(100);

ALTER TABLE Client ALTER COLUMN phone TYPE VARCHAR(15);

ALTER TABLE Product ADD COLUMN Description TEXT;

ALTER TABLE Product ALTER COLUMN Weight TYPE NUMERIC(8, 2);

ALTER TABLE Shop ADD COLUMN OpeningHours TIME;

ALTER TABLE Delivery ALTER COLUMN Price TYPE NUMERIC(9, 2);

ALTER TABLE Shipment ADD COLUMN Status VARCHAR(50);

ALTER TABLE ShipmentProduct ALTER COLUMN Count TYPE SMALLINT;

ALTER TABLE Client ALTER COLUMN Email SET NOT NULL;

ALTER TABLE ShipmentProduct DROP COLUMN IF EXISTS Count;
